import { useEffect, useRef, useState } from 'react';
import { router, Stack, useLocalSearchParams } from 'expo-router';
import { useSQLiteContext } from 'expo-sqlite';
import { Alert, Pressable, ScrollView, Text } from 'react-native';
import { WorkspaceButton, WorkspaceCard, WorkspaceField } from '@/components/workspace-controls';
import { MarkdownContent } from '@/components/markdown-content';
import { getConversation, listMessages, saveDiscussionAsNode, type ConversationMessage } from '@/data/conversations';
import { getNodeAnswer } from '@/data/node-answers';
import { colors } from '@/theme/tokens';
import { parseReadingQuestion, readableReadingText } from '@/data/reading-reference';
export default function CaptureDiscussionScreen(){
  const {conversationId,answerId,messageIds}=useLocalSearchParams<{conversationId?:string;answerId?:string;messageIds?:string}>();
  const db=useSQLiteContext();const [messages,setMessages]=useState<ConversationMessage[]>([]);const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState('');const [answer,setAnswer]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const gate=useRef(false);
  useEffect(()=>{void(async()=>{
    if(answerId){const value=await getNodeAnswer(db,answerId);if(!value)throw new Error('回答不存在');setTitle(value.question.slice(0,160));setAnswer(value.body);}
    else if(conversationId){const [chat,all]=await Promise.all([getConversation(db,conversationId),listMessages(db,conversationId)]);if(!chat)throw new Error('对话不存在');const available=all.filter(m=>m.body.trim()&&m.status!=='pending');setMessages(available);const firstQuestion=available.find(m=>m.role==='user')?.body??chat.title;setTitle((parseReadingQuestion(firstQuestion)?.question??firstQuestion).slice(0,160));const ids:unknown=messageIds?JSON.parse(messageIds):available.map(m=>m.id);if(!Array.isArray(ids)||!ids.every(id=>typeof id==='string'))throw new Error('所选消息无效');setSelected(ids);}
  })().catch(e=>setError(e.message));},[db,conversationId,answerId,messageIds]);
  async function save(){if(gate.current)return;gate.current=true;setBusy(true);setError('');try{const result=await saveDiscussionAsNode(db,{title,conversationId,answerId,messageIds:selected});Alert.alert(result.reused?'这段内容已经保存':'已保存文档并新建节点','原对话完整保留，文档中可以返回来源。',[{text:'阅读文档',onPress:()=>router.replace({pathname:'/document/[id]',params:{id:result.documentId}})},{text:'查看节点',onPress:()=>router.replace({pathname:'/project/[id]',params:{id:result.projectId,...(result.nodeId?{initialNodeId:result.nodeId}:{}),favoriteJump:'1'}})}]);}catch(e){setError(e instanceof Error?e.message:'保存失败，未创建半成品');}finally{gate.current=false;setBusy(false);}}
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{padding:18,gap:16,paddingBottom:48}}><Stack.Screen options={{title:'保存为文档和节点'}} /><Text style={{color:colors.inkMuted,lineHeight:23}}>保留选中的原文，新节点会连接到当前讨论的节点。原对话不会被修改。</Text><WorkspaceField label="节点与文档标题" value={title} onChangeText={setTitle} />{error?<Text selectable style={{color:colors.coral}}>{error}</Text>:null}{answer?<MarkdownContent value={answer} scrollEnabled={false}/>:null}{messages.length?<WorkspaceButton secondary label={selected.length===messages.length?'取消全选':'选择整段讨论'} onPress={()=>setSelected(selected.length===messages.length?[]:messages.map(m=>m.id))}/>:null}{messages.map(m=><WorkspaceCard key={m.id}><Pressable accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(m.id)}} onPress={()=>setSelected(current=>current.includes(m.id)?current.filter(id=>id!==m.id):[...current,m.id])} style={{minHeight:44,justifyContent:'center'}}><Text style={{color:selected.includes(m.id)?colors.blue:colors.ink,fontWeight:'700'}}>{selected.includes(m.id)?'已选择':'选择'} · {m.role==='user'?'我':'AI'}{m.status==='interrupted'?' · 未完成':''}</Text></Pressable><Text selectable numberOfLines={8} style={{color:colors.ink,lineHeight:23}}>{readableReadingText(m.body)}</Text></WorkspaceCard>)}<WorkspaceButton label={busy?'正在保存…':'保存文档并新建节点'} disabled={busy||!title.trim()||(!answerId&&!selected.length)} onPress={()=>void save()} /></ScrollView>;
}
