apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'

group = 'expo.modules.contentextractor'
version = '1.0.0'

android {
  namespace "expo.modules.contentextractor"

  defaultConfig {
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
  implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
}
